### ISSUE TITLE
for me the doors arent locking

### ISSUE THREAD

**Issue by jaylac2000** [Kopskink/kps-shoplift#1]
![image](https://github.com/user-attachments/assets/accf1c1d-ca21-4ec2-a5e5-45c2b2003968)

**Comment by Kopskink** [comment]
Hey, 

Are you using all of the correct dependencies? 

Check if the dependencies are all up to date (latest version).

Check if all the door names are set accordingly to the exact store.

Something that could also cause problems is if your targeting system is set as qb-target because that I did basically 0 testing on.

**Comment by Kopskink** [comment]
Redownload kps-shoplift, I think the problem should now be fixed with the 1.0.1 version.

**Comment by jaylac2000** [comment]
thanks, ill check again

**Comment by jaylac2000** [comment]
your 1.0.1 changes i did myself. your doorlock file i inserted and updated ox_doorlock, still not working

**Comment by Kopskink** [comment]
Check the code if for qb-target the arguments and data are going threw correctly.

Alternatively you could start using ox_target as it's better lol.

**Comment by jaylac2000** [comment]
the target isnt the issue.

**Comment by Kopskink** [comment]
Yes, you are right. The script is not limited to the use of only ox_target.

However at this time ox_target is correctly set up to the script and qb-target isn't passing the arguments and/or the info.

So to fix, check the code if for qb-target the arguments and data are going threw correctly.

I am sorry but currently me giving help isn't the best because I am currently on a trip and providing help on my phone.
